apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cmlvdmVyckBpbjIy
  SECRET_KEY: MDlkMjVlMDk0ZmFhNmNhMjU1NmM4MTgxNjZiN2E5NTYzYjkzZjcwOTlmNmYwZjRjYWE2Y2Y2M2I4OGU4ZDNlNw==
  ALGORITHM: SFMyNTY=
  ACCESS_TOKEN_EXPIRE_MINUTES: NjA=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-server-deployment
  labels:
    app: orders-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-server
  template:
    metadata:
      labels:
        app: orders-server
    spec:
      containers:
      - name: orders-server
        image: rioverrain/orders_server:latest
        ports:
          - containerPort: 8001
            name: http
            protocol: TCP
        env :
         - name: POSTGRES_DB
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: POSTGRES_DB
         - name: POSTGRES_USER
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: POSTGRES_USER
         - name: POSTGRES_PASSWORD
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: POSTGRES_PASSWORD
         - name: SECRET_KEY
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: SECRET_KEY   
         - name: ALGORITHM
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: ALGORITHM   
         - name: ACCESS_TOKEN_EXPIRE_MINUTES
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: ACCESS_TOKEN_EXPIRE_MINUTES         

---

apiVersion: v1
kind: Service
metadata:
  name: orders-server-service
spec:
  selector:
    app: orders-server
  ports:
    - port: 8001
