apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cmlvdmVyckBpbjIy
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-server-deployment
  labels:
    app: warehouse-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-server
  template:
    metadata:
      labels:
        app: warehouse-server
    spec:
      containers:
      - name: warehouse-server
        image: rioverrain/warehouse_server:latest
        ports:
          - containerPort: 8000
            name: http
            protocol: TCP
        env :
         - name: POSTGRES_DB
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: POSTGRES_DB
         - name: POSTGRES_USER
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: POSTGRES_USER
         - name: POSTGRES_PASSWORD
           valueFrom:
            secretKeyRef:
               name: postgres-secret
               key: POSTGRES_PASSWORD


---

apiVersion: v1
kind: Service
metadata:
  name: warehouse-server-service
spec:
  selector:
    app: warehouse-server
  ports:
    - port: 8000
